### ISSUE TITLE
RDBMS Reader throwing ConcurrentModificationException

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#225]
Application Version: 1.0.1

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.putAll(HashMap.java:784)
	at org.jumpmind.metl.core.runtime.component.RdbmsReader.prepareParams(RdbmsReader.java:161)
	at org.jumpmind.metl.core.runtime.component.RdbmsReader.handle(RdbmsReader.java:133)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:301)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.lambda$process$0(StepRuntime.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by abrougher** [comment]
This was caused by a specific flow manipulating context parameters via script component at the same time as multiple RDBMS Reader components were reading in the context parameters. The context.parameters
