### ISSUE TITLE
The XML Formatter component is throwing an exception.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#300]
``` java

java.lang.IndexOutOfBoundsException: Index: 0 Size: 0
	at org.jdom2.ContentList$FilterList.get(ContentList.java:1121)
	at org.jdom2.ContentList$FilterList.get(ContentList.java:908)
	at org.jumpmind.metl.core.runtime.component.XmlFormatter.fillStackWithStaticParentElements(XmlFormatter.java:228)
	at org.jumpmind.metl.core.runtime.component.XmlFormatter.addXmlElement(XmlFormatter.java:178)
	at org.jumpmind.metl.core.runtime.component.XmlFormatter.processMsgEntities(XmlFormatter.java:161)
	at org.jumpmind.metl.core.runtime.component.XmlFormatter.createXml(XmlFormatter.java:132)
	at org.jumpmind.metl.core.runtime.component.XmlFormatter.handle(XmlFormatter.java:116)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:312)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.process(StepRuntime.java:292)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.run(StepRuntime.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by gwilmer** [comment]
Working on this...
