### ISSUE TITLE
Make the JMS topic directory resource more resilient to session outages

### ISSUE THREAD

**Issue by chenson42** [JumpMind/metl#345]

**Comment by chenson42** [comment]
`Failed to send file on try 1: java.lang.RuntimeException: javax.jms.IllegalStateException: JMS-131: Session is closed
	at org.jumpmind.metl.core.runtime.resource.JMSJndiTopicDirectory$CloseableOutputStream.close(JMSJndiTopicDirectory.java:143)
	at org.jumpmind.metl.core.runtime.component.RTLog.saveRtLog(RTLog.java:292)
	at org.jumpmind.metl.core.runtime.component.RTLog.finish(RTLog.java:269)
	at org.jumpmind.metl.core.runtime.component.RTLog.handle(RTLog.java:204)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:312)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.lambda$process$2(StepRuntime.java:290)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.jms.IllegalStateException: JMS-131: Session is closed
	at oracle.jms.AQjmsError.throwIllegalStateEx(AQjmsError.java:471)
	at oracle.jms.AQjmsSession.checkSessionStarted(AQjmsSession.java:4736)
	at oracle.jms.AQjmsSession.createMapMessage(AQjmsSession.java:678)
	at org.jumpmind.metl.core.runtime.resource.JMSJndiTopicDirectory$CloseableOutputStream.close(JMSJndiTopicDirectory.java:127)
	... 8 more`
