### ISSUE TITLE
NPE thrown when importing a new model from a database.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#368]

**Comment by abrougher** [comment]
Caused by: java.lang.NullPointerException
	at org.jumpmind.metl.ui.common.UiUtils.getFilterMatchRange(UiUtils.java:64)
	at org.jumpmind.metl.ui.common.UiUtils.getName(UiUtils.java:43)
	at org.jumpmind.metl.ui.views.design.EditModelPanel$3.generateCell(EditModelPanel.java:195)
	at com.vaadin.ui.Table.parseItemIdToCells(Table.java:2364)
	at com.vaadin.ui.Table.getVisibleCellsNoCache(Table.java:2225)
	at com.vaadin.ui.Table.refreshRenderedCells(Table.java:1745)
