### ISSUE TITLE
Fixed Length Formater fails when attribute includes transform.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#657]
To recreate:
Update sample flow "Relational Database To Flat File". Add the transform "upper();" to the first name attribute on the fixed length formatter. 
Witness the following error...

```
java.lang.RuntimeException: Unable to evaluate groovy script.  Attribute ==> FIRST_NAME.  Value ==> Garfield.startup failed:
Script34.groovy: 1: unable to resolve class org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper
 @ line 1, column 1.
   import org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper;
   ^

1 error

	at org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper.eval(ModelAttributeScriptHelper.java:452)
	at org.jumpmind.metl.core.runtime.component.FixedLengthFormatter.processInputRow(FixedLengthFormatter.java:123)
	at org.jumpmind.metl.core.runtime.component.FixedLengthFormatter.handle(FixedLengthFormatter.java:109)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:341)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.process(StepRuntime.java:308)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.run(StepRuntime.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.script.ScriptException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script34.groovy: 1: unable to resolve class org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper
 @ line 1, column 1.
   import org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper;
   ^

1 error

	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper.eval(ModelAttributeScriptHelper.java:449)
	... 8 more
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script34.groovy: 1: unable to resolve class org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper
 @ line 1, column 1.
   import org.jumpmind.metl.core.runtime.component.ModelAttributeScriptHelper;
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:946)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:211)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:363)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:150)
	... 10 more
```

**Comment by abrougher** [comment]
Issue does not happen when running local within eclipse. Assume class path issue on installed version. Running version version 2.0.0.a.201702021435.
