### ISSUE TITLE
Error when using metl with MySQL as metl-configuration db

### ISSUE THREAD

**Issue by lifeofguenter** [JumpMind/metl#729]
Getting a 503 when trying to visit the metl-url when using MySQL as configuration db.

```
$ cat metl.properties
db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://localhost/foobar?user=foobar&password=foobar
db.user=foobar
db.password=foobar
```

```
$ head metl_service.conf
#********************************************************************
# Wrapper Java Properties
#********************************************************************

# Java Runtime Executable
wrapper.java.command=java

# Java Classpath
wrapper.java.classpath.1=/home/guenter/metl-2.0.4.r.63.war:/home/guenter/jdbc/driver/mysql-connector.jar
```

Error:

```
2017-05-29 22:09:43,214 INFO  [AppConfig] [main] About to initialize the configuration datasource using the following driver: 'com.mysql.jdbc.Driver' and the following url: 'jdbc:mysql://localhost/foobar?user=foobar&password=foobar' and the following user: 'foobar'
2017-05-29 22:09:43,300 INFO  [AppConfig] [main] About to initialize the execution datasource using the following driver: 'com.mysql.jdbc.Driver' and the following url: 'jdbc:mysql://localhost/foobar?user=foobar&password=foobar' and the following user: 'foobar'
2017-05-29 22:09:51,829 INFO  [ExecutionService] [main] Scheduling the purge job to run every 3600000ms.  The first scheduled run time is at Mon May 29 23:09:51 UTC 2017
2017-05-29 22:09:52,285 WARN  [BrokerService] [main] Temporary Store limit is 51200 mb (current store usage is 0 mb). The data directory: /home/guenter only has 3801 mb of usable space. - resetting to maximum available disk space: 3801 mb
2017-05-29 22:09:52,988 INFO  [ConfigDatabaseUpgrader] [main] Checking if config tables need created or altered
2017-05-29 22:09:53,373 INFO  [ConfigDatabaseUpgrader] [main] Checking if config tables need created or altered
2017-05-29 22:09:53,394 INFO  [AppInitializer] [main] The configuration database has been initialized
2017-05-29 22:09:53,464 INFO  [PluginManager] [main] Initializing plugin manager.  The local repository is located at: /home/guenter/plugins
2017-05-29 22:09:53,779 WARN  [WebAppContext] [main] Failed startup of context o.e.j.w.WebAppContext@1134affc{/metl,[file:///home/guenter/metl-2.0.4.r.63/, jar:file:///home/guenter/metl-2.0.4.r.63/WEB-INF/lib/springfox-swagger-ui-2.6.0.jar!/META-INF/resources],UNAVAILABLE}{file:/home/guenter/metl-2.0.4.r.63.war}
org.jumpmind.db.sql.SqlException: Failed to execute sql: select distinct artifact_group, artifact_name, load_order from (select v.artifact_group, v.artifact_name, p.load_order from metl_project_version_definition_plugin v left join  metl_plugin p on v.artifact_name=p.artifact_name and v.artifact_group=p.artifact_group where v.enabled=1)  order by load_order, artifact_group, artifact_name
	at org.jumpmind.db.sql.AbstractSqlTemplate.translate(AbstractSqlTemplate.java:300)
	at org.jumpmind.db.sql.JdbcSqlReadCursor.<init>(JdbcSqlReadCursor.java:120)
	at org.jumpmind.db.sql.JdbcSqlTemplate.queryForCursor(JdbcSqlTemplate.java:140)
	at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:199)
	at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:195)
	at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:185)
	at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:121)
	at org.jumpmind.metl.core.persist.PluginService.findActivePlugins(PluginService.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy68.findActivePlugins(Unknown Source)
	at org.jumpmind.metl.core.plugin.PluginManager.checkForNewConfiguredVersions(PluginManager.java:188)
	at org.jumpmind.metl.core.plugin.PluginManager.refresh(PluginManager.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy70.refresh(Unknown Source)
	at org.jumpmind.metl.core.plugin.DefinitionFactory.refresh(DefinitionFactory.java:107)
	at org.jumpmind.metl.ui.definition.DefinitionPlusUIFactory.refresh(DefinitionPlusUIFactory.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy71.refresh(Unknown Source)
	at org.jumpmind.metl.ui.init.AppInitializer.initPlugins(AppInitializer.java:168)
	at org.jumpmind.metl.ui.init.AppInitializer.contextInitialized(AppInitializer.java:180)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.jumpmind.metl.StartWebServer.runWebServer(StartWebServer.java:149)
	at org.jumpmind.metl.StartWebServer.main(StartWebServer.java:99)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Every derived table must have its own alias
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.jumpmind.db.sql.JdbcSqlReadCursor.<init>(JdbcSqlReadCursor.java:97)
	... 66 more
```

When copy-pasted into mysql-cli:

```
mysql> select distinct artifact_group, artifact_name, load_order from (select v.artifact_group, v.artifact_name, p.load_order from metl_project_version_definition_plugin v left join  metl_plugin p on v.artifact_name=p.artifact_name and v.artifact_group=p.artifact_group where v.enabled=1)  order by load_order, artifact_group, artifact_name;
ERROR 1248 (42000): Every derived table must have its own alias
```

**Comment by gwilmer** [comment]
We don't actually support a non-h2 database for the config database right now.  We have quite a few large clients using with H2 databases as the config and execution database.  We do want to open it up to allow any jdbc compliant database for config db, but not done yet.

**Comment by spyhunter88** [comment]
Hi,
We try to use H2 database but some unexpected errors might appear, this cause my cron job stop. I don't know exactly why, but sometimes it locked or , I need to erase all H2 DB's file and re-create all my projects.

Right now I get `transaction is closed (1.4.193/4)`

**Comment by gwilmer** [comment]
Metl should now be able to use any jdbc complaint data source for its configuration and execution databases.  The default is still H2.

*** NOTE ***
As part of this change, the default development database names (OLD - metl-dev and metl-exec) have been changed to (NEW-  metldev and metlexec).  If upgrading to this version of metl and you are using the default h2 databases, you will need to do the following during upgrade:

1.  Before upgrading export your current projects
2.  Change jdbc urls in the metl.properties file from metl-dev to metldev and metl-exec to metlexec
3.  Start metl
4.  Import existing configuration

**Comment by marina-saad** [comment]
Cannot open any component in flows 
shows an error of sql executor 
error message 
Could not find the component definition for a component of type 'Sql Executor' and project version

**Comment by nrichardson99** [comment]
Did you just do a new install?  Was this an existing install where this just started happening?
There was an issue recently identified where Metl was not able to download the plugins (https://github.com/JumpMind/metl/issues/939).  This fix has not been released if this is your case but you can go to Admin Plugin Repository and update the link for the repository to be https instead and then restart Metl.

**Comment by marina-saad** [comment]
new install
