### ISSUE TITLE
Sending POST request not working from execute component nor from web request component

### ISSUE THREAD

**Issue by abismail** [JumpMind/metl#736]
Hey guys,

I'm trying to send a curl request from an execute component. but it seems like my command is not being reconstructed correctly and so my options are not being recognized.

here's my command:
`curl -X POST -F 'authtoken=7b8d87b330da0574973695ba981ea739' -F 'scope=crmapi' -F 'xmlData=<Leads><row no="1"><FL val="Lead Source">Metl curl post</FL><FL val="Company">BIG ROAM -
 curl test</FL><FL val="First Name">big</FL><FL val="Last Name">Roam</FL><FL val="Email">postman@testing.com</FL></row></Leads>' https://crm.zoho.com/crm/private/xml/Leads/insertRecords`

And this is what I get from the log:

About to execute: {curl,-X,POST,-F,'authtoken=7b8d87b330da0574973695ba981ea739',-F,'scope=crmapi',-F,'xmlData=<Leads><row,no="1"><FL,val="Lead,Source">Metl,curl,post</FL><FL,val="Company">BIG,ROAM,-,curl,test</FL><FL,val="First,Name">big</FL><FL,val="Last,Name">Roam</FL><FL,val="Email">postman@testing.com</FL></row></Leads>',https://crm.zoho.com/crm/private/xml/Leads/insertRecords}
The output of the command was: curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
org.jumpmind.exception.IoException: {curl,-X,POST,-F,'authtoken=73695ba981ea7397b8d87b330da05749',-F,'scope=crmapi',-F,'xmlData=<Leads><row,no="1"><FL,val="Lead,Source">Metl,curl,post</FL><FL,val="Company">BIG,ROAM,-,curl,test</FL><FL,val="First,Name">big</FL><FL,val="Last,Name">Roam</FL><FL,val="Email">postman@testing.com</FL></row></Leads>',https://crm.zoho.com/crm/private/xml/Leads/insertRecords} failed with an error code of 2
	at org.jumpmind.metl.core.runtime.component.Execute.handle(Execute.java:121)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:350)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.process(StepRuntime.java:316)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.run(StepRuntime.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

PS: that authToken is not a valid one, but I have run the command from my terminal and it works, it just doesn't work in metl.

The reason I'm using an execute component is because the web service component only works when I send a GET request, when I send a POST I get this error:
org.jumpmind.exception.IoException: Received an unexpected response code of 505
	at org.jumpmind.metl.core.runtime.resource.HttpDirectory.getInputStream(HttpDirectory.java:191)
	at org.jumpmind.metl.core.runtime.component.Web.handle(Web.java:146)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:350)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.process(StepRuntime.java:316)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.run(StepRuntime.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

I'd appreciate any help please, thanks!

**Comment by abismail** [comment]
moved my post params to the Http Parameters field and formatted them like this:
field_name1:value1
field_name2:value2

this could be better explained or an example of the format could be a placeholder in the field, so as to be more descriptive.

Thanks!
