### ISSUE TITLE
Modell-Diff: Get diff of two RDBMS Readers with same data-model

### ISSUE THREAD

**Issue by stefanhenz** [JumpMind/metl#845]
Hi,

we try to diff two tables from different databases. Both tables are storing "company" information. We would like to compare the two dataset's and update (modify existing and insert new) the target table.

Currently we are using the "Model Data Diff" component and we receive an SQL Error message. 
Here the error message:

```
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select from companies_2 curr left join companies_1 orig on  where ]; nested exception is org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT FROM COMPANIES_2 CURR LEFT JOIN COMPANIES_1 ORIG ON  WHERE[*]  "; expected "NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
select from companies_2 curr left join companies_1 orig on  where  [42001-194]
```
This is our Test-Flow:
![image](https://user-images.githubusercontent.com/33940613/42170825-e241280c-7e17-11e8-9952-3aa57c9c632c.png)

Any advice will be appreciated.

Best regards

Stefan

**Comment by nrichardson99** [comment]
What version of Metl are you using?  Could you export this flow and attach the .json file so we could take a look at your setup?

**Comment by abrougher** [comment]
The SQL being built appears to be missing columns to join on. "....orig on  where ..."

Without looking at code, my guess is its using your defined model's PK to join on. Do you have a PK defined on your model? Could you add one and see if this fixes your issue?

If we determine that a PK must be defined, we should at a minimum throw a better error message before trying to execute incorrectly formed SQL. 

Thanks

**Comment by stefanhenz** [comment]
Hi

We are using the current release of metl. We defined a PK in the model and got a different error message.

Error-Message:
`
Error in flow 01_import-iet-company on agent <default user on srv-virt-dbtransfer> at 09:29:03 on 2018-07-03

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select from companies_2 curr left join companies_1 orig on curr."IET_COMPANY_ID"=orig."IET_COMPANY_ID" where orig."IET_COMPANY_ID" is null]; nested exception is org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT FROM COMPANIES_2 CURR LEFT JOIN COMPANIES_1 ORIG ON CURR.""IET_COMPANY_ID""=ORIG.""IET_COMPANY_ID"" WHERE[*] ORIG.""IET_COMPANY_ID"" IS NULL "; expected "(, ., [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from companies_2 curr left join companies_1 orig on curr."IET_COMPANY_ID"=orig."IET_COMPANY_ID" where orig."IET_COMPANY_ID" is null [42001-194]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:645)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:680)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:707)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:154)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:161)
	at org.jumpmind.metl.core.runtime.component.RdbmsReader.handle(RdbmsReader.java:156)
	at org.jumpmind.metl.core.runtime.component.DataDiff.calculateDiff(DataDiff.java:264)
	at org.jumpmind.metl.core.runtime.component.DataDiff.handle(DataDiff.java:145)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.processOnAnotherThread(StepRuntime.java:350)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.process(StepRuntime.java:316)
	at org.jumpmind.metl.core.runtime.flow.StepRuntime.run(StepRuntime.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT FROM COMPANIES_2 CURR LEFT JOIN COMPANIES_1 ORIG ON CURR.""IET_COMPANY_ID""=ORIG.""IET_COMPANY_ID"" WHERE[*] ORIG.""IET_COMPANY_ID"" IS NULL "; expected "(, ., [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from companies_2 curr left join companies_1 orig on curr."IET_COMPANY_ID"=orig."IET_COMPANY_ID" where orig."IET_COMPANY_ID" is null [42001-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.getSyntaxError(DbException.java:205)
	at org.h2.command.Parser.getSyntaxError(Parser.java:539)
	at org.h2.command.Parser.read(Parser.java:3242)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2070)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1928)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1746)
	at org.h2.command.Parser.parseSelect(Parser.java:1734)
	at org.h2.command.Parser.readTerm(Parser.java:2833)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:2041)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2073)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1928)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1746)
	at org.h2.command.Parser.parseSelect(Parser.java:1734)
	at org.h2.command.Parser.parsePrepared(Parser.java:447)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:295)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:623)
	... 13 more
`

I attached you the json-file of the flow without the database connection. 
[flow.zip](https://github.com/JumpMind/metl/files/2158107/flow.zip)


Thanks

**Comment by stefanhenz** [comment]
Hi 

I fixed it. I don't like the behaviour of the component which is not passing the Model PK through. 
But now it works. 

Thanks for your help
