### ISSUE TITLE
RDBMS-Writer: How to pass custom Enum-types

### ISSUE THREAD

**Issue by stefanhenz** [JumpMind/metl#857]
Hi 

We try to write custom Enum-Types over RDBMS Writer to the database. We changed the Modell-field type "OTHER" but this has no positive effect. 

This is the insert statement:
`Failed to run the following sql: 
insert into public.access_requests (requester_id, grantor_id, room_id, status, notes, access_from, access_to) values (?,?,?,?,?,?,?)
With values: 
[89, null, 32, allowed, Störung bei der Umluft kühler Nr.2. |  Firma ACME AG und ABC., null, null]
With types: 
[-5, -5, -5, -1, -1, 93, 93]`

resulting in the following error messages:

`org.jumpmind.db.sql.SqlException: ERROR: column "status" is of type access_request_status but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 128
	at org.jumpmind.db.sql.AbstractSqlTemplate.translate(AbstractSqlTemplate.java:300)
	at org.jumpmind.db.sql.AbstractSqlTemplate.translate(AbstractSqlTemplate.java:291)
	at org.jumpmind.db.sql.JdbcSqlTransaction.addRow(JdbcSqlTransaction.java:463)
	at org.jumpmind.metl.core.runtime.component.RdbmsWriter.execute(RdbmsWriter.java:507)
	at org.jumpmind.metl.core.runtime.component.RdbmsWriter.executeSql(RdbmsWriter.java:410)
	at org.jumpmind.metl.core.runtime.component.RdbmsWriter.executeSqlInserts(RdbmsWriter.java:392)`

This is a part of the error message we got.

Do you have any clue? 

Best Regards

Stefan Henz

**Comment by gwilmer** [comment]
Stefan.  I don't think the RDBS writer will support the custom types at this point.  I will take a look at it sometime in the next week to see what options are available.
