### ISSUE TITLE
An exeception throws when i build project for generate metl.war

### ISSUE THREAD

**Issue by AubryYvan** [JumpMind/metl#951]
Task :metl-war:vaadinCompile

Unexpected internal compiler error
java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)

I use Java jdk 8  on windows 10 and gradle 4.10.2 is automatically install.

**Comment by azizkhani** [comment]
+

**Comment by azizkhani** [comment]
How did you solve the problem?
